### PR TITLE
Added XRC to coin list

### PR DESCRIPTION
**Pull request by xrhodium**
Hello,
please to add X11 - XRC to coin list in miningcore.

Thank you.

https://xrhodium.org/

### CODE REVIEW

**Comment by oliverw** [comment]
Did you test this?

**Comment by xrhodium** [comment]
Yes there are two instances:

Testnet pool:
http://tpool.xrhodium.org/

Production pool:
http://poolcore.xrhodium.org/

And wiki how to setup new miningcore pool:
https://github.com/XRCPlatform/xrhodiumnode/wiki/How-to-setup-new-MiningCore-pool-for-XRC

Thank you :)

**Comment by oliverw** [comment]
> Yes there are two instances:
> 
> Testnet pool: http://tpool.xrhodium.org/
> 
> Production pool: http://poolcore.xrhodium.org/
> 
> And wiki how to setup new miningcore pool: https://github.com/XRCPlatform/xrhodiumnode/wiki/How-to-setup-new-MiningCore-pool-for-XRC
> 
> Thank you :)

No I wanted to know if you tested your stuff. Its not my job to test your stuff.

**Comment by xrhodium** [comment]
This coins.json file is used on [tpool](http://tpool.xrhodium.org/). :) It is working ;)

**Pull request merged**
