### PR TITLE
Fix Linux Build

### PR DESCRIPTION
**Pull request by lurchinms**
This works for me on Ubuntu 20.04

### CODE REVIEW

**Comment by lurchinms** [comment]
image

**Comment by lurchinms** [comment]
It passes build on my Visual Studio Code, my server and it show 0 Warning(s) and 0 Error(s)

**Comment by lurchinms** [comment]
image

**Comment by lurchinms** [comment]
Hmm, this is interesting.

**Comment by oliverw** [comment]
PR's should be filed against the `dev` branch.

**Comment by oliverw** [comment]
Why are you mixing new functionality with a build fix?

**Comment by lurchinms** [comment]
Because it builds on Linux

**Comment by oliverw** [comment]
> Because it builds on Linux

That makes no sense.

**Comment by lurchinms** [comment]
Some how my Github was connected to yours. Should be fixed now.

**Pull request closed without merging**
