### PR TITLE
Add Docker building

### PR DESCRIPTION
**Pull request by warren-ru**

### CODE REVIEW

**Comment by oliverw** [comment]
Thanks for the PR. Wouldn't it be more useful to have continous deployment to dockerhub instead of providing build instructions?

**Comment by warren-ru** [comment]
It's not a docker image.
You get "build" folder for using with target OS

**Comment by warren-ru** [comment]
If you have Docker engine installed, you just pull .NET image, build the app and that's all. You system remains much more clean as for me.

**Comment by oliverw** [comment]
Right, LGTMT.

**Pull request merged**
