### PR TITLE
Fix NiceHash for ERGO

### PR DESCRIPTION
**Pull request by belmix**
Checked works thx Konstantin35

### CODE REVIEW

**Comment by belmix** [comment]
image
image
image
image

**Comment by oliverw** [comment]
This change is not compatible with many miners and won't be merged in this form. If this was conditional for Nicehash only, that might be a different story.

**Comment by belmix** [comment]
in which case would it be incompatible?

**Comment by oliverw** [comment]
> in which case would it be incompatible?

Miner apps expect diff = 1

**Comment by oliverw** [comment]
Could you just make the change apply only when Nicehash is detected?

**Comment by oliverw** [comment]
Any update on this?

**Comment by belmix** [comment]
yes, there is a solution, it takes time

**Comment by oliverw** [comment]
Implemented in 48c4fe91608cc37884cb3c9846afb3a2b14305d6.

**Pull request closed without merging**
