### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by konstiantyn**
Fixed zencash founder fee.

### CODE REVIEW

**Comment by oliverw** [comment]
Has this been tested?

**Comment by konstiantyn** [comment]
Yes. I tested.

**Comment by oliverw** [comment]
> Yes. I tested.

Great work. Thanks a lot for your contribution.

**Comment by oliverw** [comment]
> Yes. I tested.

So Zencash is working again with your patch?

**Comment by konstiantyn** [comment]
Yes. It works for me

**Pull request merged**
