### PR TITLE
Ethereum share rejection

### PR DESCRIPTION
**Pull request by konstiantyn**
Ethereum share rejection

### CODE REVIEW

**Comment by oliverw** [comment]
So why does this PR fix the problem?

**Comment by konstiantyn** [comment]
Amost share rejected in ASIC miners.

**Comment by konstiantyn** [comment]
I have tested it already. V1 and V2 protocol work in Phoeniex and lolminer well. But Gminer and Trex don't work.
I tried to rent from MRR. But they said "We were unable to establish a connection to the pool you provided."

**Comment by oliverw** [comment]
> Amost share rejected in ASIC miners.

My question was not what it is supposed to do but why it fixes the problem. I don't understand why those changes would help with low difficulty shares?

**Comment by konstiantyn** [comment]
Since Vardiff does not know the previous difficulty, it sets a new vardiff value.

**Comment by oliverw** [comment]
> Since Vardiff does not know the previous difficulty, it sets a new vardiff value.

Where does it set a new difficulty?

**Comment by konstiantyn** [comment]
https://github.com/konstiantyn/miningcore-1/blob/patch-1/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs#L215-L216
Here

**Comment by oliverw** [comment]
> https://github.com/konstiantyn/miningcore-1/blob/patch-1/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs#L215-L216 Here

1. That sends the current difficulty again. It does not set a new one. 
2. It sends a notification after a share submission which is not exactly whats in the spec
3. It sends a v2 notifications to v1 clients

**Pull request closed without merging**
