### PR TITLE
Dockerfile to run minercore

### PR DESCRIPTION
**Pull request by snoby**
This Docker file will build and run minercore.
It will do the build and then transfer the resultant binaries to a new (smaller container).

### CODE REVIEW

**Comment by oliverw** [comment]
Why the very specific ubuntu version?

**Comment by jon4hz** [comment]
What about the following Dockerfile using microsofts dotnet container as base?


```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-jammy as BUILDER
WORKDIR /app 
RUN apt-get update && \
    apt-get -y install cmake build-essential libssl-dev pkg-config libboost-all-dev libsodium-dev libzmq5 libzmq3-dev golang-go
COPY . .
WORKDIR /app/src/Miningcore
RUN dotnet publish -c Release --framework net6.0 -o ../../build

FROM mcr.microsoft.com/dotnet/aspnet:6.0-jammy
WORKDIR /app
RUN apt-get update && \
    apt-get install -y libzmq5 libzmq3-dev && \
    apt-get clean
COPY --from=BUILDER /app/build ./
CMD ["./Miningcore", "-c", "config.json" ]
```

**Comment by jon4hz** [comment]
Just noticed that libsodium might be missing in the last stage. Afaik this is required for the encryption of the zmq connection. 

@oliverw are there any other runtime dependencies missing?

**Comment by snoby** [comment]
> Why the very specific ubuntu version?

There were issues with mismatched .dotnet versions if I didn't use the latest version.

**Comment by oliverw** [comment]
> Just noticed that libsodium might be missing in the last stage. Afaik this is required for the encryption of the zmq connection.
> 
> @oliverw are there any other runtime dependencies missing?

LGTM.

**Comment by oliverw** [comment]
> > Why the very specific ubuntu version?
> 
> There were issues with mismatched .dotnet versions if I didn't use the latest version.

Is this done?

**Comment by snoby** [comment]
> > > Why the very specific ubuntu version?
> > 
> > 
> > There were issues with mismatched .dotnet versions if I didn't use the latest version.
> 
> Is this done?

I've been running it and I think it looks good!

**Comment by oliverw** [comment]
> ```dockerfile
> mcr.microsoft.com/dotnet/sdk:6.0-jammy
> ```

What about image `mcr.microsoft.com/dotnet/sdk:6.0-jammy` as suggested by @jon4hz ?

**Comment by snoby** [comment]
> > I've been running it and I think it looks good!
> 
> What about image `mcr.microsoft.com/dotnet/sdk:6.0-jammy` as suggested by @jon4hz ?

Yes that's what i've been running.  I will update the PR and push.

**Comment by oliverw** [comment]
Thanks for your contribution 👍 

(Future PRs please against `dev`)

**Comment by jon4hz** [comment]
@oliverw I think you merged this a bit to early. @snoby wanted to push some changes first :sweat_smile:

**Comment by oliverw** [comment]
> @oliverw I think you merged this a bit to early. @snoby wanted to push some changes first 😅

True. @snoby opinions?

**Comment by snoby** [comment]
I would agree, I've been testing in production on vipor.net the Dockerfile that @jon4hz  suggested which has been working great!
 
 
 However building against  master on a 3900x linux machine results in an unrecognized command line option currently 
 ```
   rm -f libcryptonight.so exports.o xmrig/crypto/cn/asm/cn_main_loop.o xmrig/crypto/cn/asm/CryptonightR_template.o xmrig/crypto/cn/r/CryptonightR_gen.o xmrig/crypto/cn/gpu/cn_gpu_avx.o xmrig/crypto/cn/gpu/cn_gpu_ssse3.o xmrig-override/backend/cpu/platform/BasicCpuInfo.o xmrig-override/backend/cpu/Cpu.o c29b.o c29i.o c29s.o c29v.o xmrig/crypto/cn/c_blake256.o xmrig/crypto/cn/c_groestl.o xmrig/crypto/cn/c_jh.o xmrig/crypto/cn/c_skein.o xmrig/base/crypto/keccak.o xmrig/base/crypto/sha3.o xmrig/crypto/cn/CnCtx.o xmrig/crypto/cn/CnHash.o xmrig/crypto/common/MemoryPool.o xmrig/crypto/common/VirtualMemory.o xmrig/crypto/common/VirtualMemory_unix.o xmrig/3rdparty/argon2/lib/argon2.o xmrig/3rdparty/argon2/lib/core.o xmrig/3rdparty/argon2/lib/encoding.o xmrig/3rdparty/argon2/lib/genkat.o xmrig/3rdparty/argon2/lib/impl-select.o xmrig/3rdparty/argon2/lib/blake2/blake2.o xmrig/3rdparty/argon2/arch/x86_64/lib/argon2-arch.o xmrig/3rdparty/argon2/arch/x86_64/lib/argon2-avx2.o xmrig/3rdparty/argon2/arch/x86_64/lib/argon2-avx512f.o xmrig/3rdparty/argon2/arch/x86_64/lib/argon2-sse2.o xmrig/3rdparty/argon2/arch/x86_64/lib/argon2-ssse3.o xmrig/3rdparty/argon2/arch/x86_64/lib/argon2-xop.o xmrig/crypto/astrobwt/AstroBWT.o xmrig/crypto/astrobwt/Salsa20.o xmrig/crypto/astrobwt/salsa20_ref/salsa20.o xmrig/crypto/ghostrider/sph_blake.o xmrig/crypto/ghostrider/sph_bmw.o xmrig/crypto/ghostrider/sph_cubehash.o xmrig/crypto/ghostrider/sph_echo.o xmrig/crypto/ghostrider/sph_fugue.o xmrig/crypto/ghostrider/sph_groestl.o xmrig/crypto/ghostrider/sph_hamsi.o xmrig/crypto/ghostrider/sph_hamsi_helper.o xmrig/crypto/ghostrider/sph_jh.o xmrig/crypto/ghostrider/sph_keccak.o xmrig/crypto/ghostrider/sph_luffa.o xmrig/crypto/ghostrider/sph_sha2.o xmrig/crypto/ghostrider/sph_shabal.o xmrig/crypto/ghostrider/sph_shavite.o xmrig/crypto/ghostrider/sph_simd.o xmrig/crypto/ghostrider/sph_skein.o xmrig/crypto/ghostrider/sph_whirlpool.o xmrig-override/crypto/ghostrider/ghostrider.o xmrig/3rdparty/libethash/keccakf800.o
  g++ -DCPU_INTEL -g -std=gnu++11 -s -fPIC -DNDEBUG -Ofast -fno-fast-math -fexceptions -fno-rtti -Wno-class-memaccess -w -maes       -D__AES__       -I. -Ixmrig/3rdparty/argon2/include -Ixmrig/3rdparty/argon2/lib -Ixmrig -Ixmrig-override   -c -o exports.o exports.cpp
  make: *** [<builtin>: bcrypt.o] Error 1
cc : error : unrecognized command-line option '-maes' [/app/src/Miningcore/Miningcore.csproj]
  make: *** [<builtin>: internal.o] Error 1
g++ : error : unrecognized command-line option '-maes' [/app/src/Miningcore/Miningcore.csproj]
  make: *** [<builtin>: exports.o] Error 1
g++ : error : unrecognized command-line option '-maes' [/app/src/Miningcore/Miningcore.csproj]
  make: *** [<builtin>: exports.o] Error 1
  Cloning into 'RandomX'...

```
I don't know if the reason for this is the define that is hard coded `-DCPU_INTEL ` or not.

**Comment by jon4hz** [comment]
I'm far from an expert on these things but I was able to build miningcore on a 5950x without any issues

**Pull request merged**
