### PR TITLE
Fixes the build issue with Linux "Miningcore.csproj(123,9): error MSB307"

### PR DESCRIPTION
**Pull request by machinasapiens**
Solves the build problem on Linux.

>/home//miningcore/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: The command "(cd /home//miningcore/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)" exited with code -1.

I moved the call to src/build-libs-linux.sh out of src/Miningcore.csproj and placed it inside the linux build files. This way the linux files will be built outside of "dotnet publish". 

Hope this helps people trying to build Miningcore on Linux Debian and Ubuntu (including VMs).

### CODE REVIEW

**Comment by machinasapiens** [comment]
I also added Outracoin to the list of coins at src/Miningcore/coins.json

**Comment by machinasapiens** [comment]
Closed the pull request due to lack of answer after 13 days.

**Comment by seperatis** [comment]
Re-opening this for review by the Lead maintainer.

**Review by machinasapiens — COMMENTED** [review]
.

**Comment by oliverw** [comment]
Hmm. Tests are failing.

**Comment by seperatis** [comment]
Strange, I'm pretty sure it was passing before he closed it. Not sure why re-opening it would have caused failed checks.... @machinasapiens

**Comment by oliverw** [comment]
> Strange, I'm pretty sure it was passing before he closed it. Not sure why re-opening it would have caused failed checks.... @machinasapiens

That's really weird.

**Comment by oliverw** [comment]
I'd really like to merge this PR but the test failure is not ideal.

**Comment by machinasapiens** [comment]
It is because I introduced a new coin into coins.json in my fork and I do not know why Github freaked out. Then I reverted and copied your coins.json to my fork and Guthub freakness continued. Forget it. I am done with it. Take care.

**Comment by seperatis** [comment]
I'll spin up some builds on Ubuntu and Debian and see what happens. Give me a couple of days and I'll submit a fix for this.
Does anyone know what `version` this build problem started with? I didn't start seeing complaints until recently...

**Comment by lurchinms** [comment]
@seperatis 
https://github.com/oliverw/miningcore/issues/1311#issuecomment-1186536826

**Pull request closed without merging**
